# Generated by Django 3.2.9 on 2021-11-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGrupal_3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencia'], [3, 'felicitaciones']])),
                ('mesaje', models.TextField()),
                ('avisos', models.BooleanField()),
            ],
        ),
    ]
