# Generated by Django 3.2.9 on 2021-11-24 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGrupal_3', '0002_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='mesaje',
            new_name='mensaje',
        ),
    ]
