# Generated by Django 3.2.9 on 2021-12-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGrupal_3', '0004_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='image',
            field=models.ImageField(upload_to='appGrupal_3/image/'),
        ),
    ]
