# Generated by Django 3.2.9 on 2021-12-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGrupal_3', '0005_auto_20211130_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='url',
        ),
        migrations.AlterField(
            model_name='productos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
