# Generated by Django 3.2.9 on 2021-12-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGrupal_3', '0006_auto_20211130_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
