# Generated by Django 3.2.9 on 2021-12-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGrupal_3', '0008_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='nombre',
            new_name='pelicula',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='precio',
        ),
        migrations.AddField(
            model_name='productos',
            name='url',
            field=models.CharField(default='null', max_length=300),
            preserve_default=False,
        ),
    ]
