# Generated by Django 3.2.9 on 2021-12-17 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGrupal_3', '0010_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
